### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by perlindgren** [TeXitoi/rusty-clock#11]
Hi

Nice work with the rusty-clock! 

Is there a reason the README.md reads:

Compiling and flashing

For compiling and flashing, please refer to the blue pill quickstart. Note that a nightly toolchain is required.

It should compile under stable (if the application itself does not use some nightly feature).

Best regards
  Per

**Comment by TeXitoi** [comment]
Thanks, forgot to update this.

**Comment by TeXitoi** [comment]
It compiles on stable since #5 is closed, a week ago.
