### ISSUE TITLE
Program the flash memory

### ISSUE THREAD

**Issue by gbip** [TeXitoi/rusty-clock#13]
Just a quick question, because I have troubles in a project of my own. How do you tell openocd to write your program into the flash memory ?
As I understand, the `load` instruction in `openocd.gdb` only load the program in RAM.
Thank you ! :smile:

**Comment by TeXitoi** [comment]
using gdb, `load` load the program in flash.

**Comment by gbip** [comment]
Thanks, I thought that this was my problem... I will open an issue in the hal repo. Thank you !

**Comment by TeXitoi** [comment]
Welcome.

**Comment by TeXitoi** [comment]
If you have a problem that look like it's working only when the debugger is plugged, there are mainly 2 reasons:
 - you use semihosting, and any printing block your program without a debugger
 - you rely on the debugger cycle counter, and it is not started automatically when the debugger is not plugged.
